export { Home } from './Home'
export { HistoryPageWithModal } from './History'
export { Dashboard } from './Dashboard'
export { Instructions } from './Instructions'
export { About } from './About'
export { Landing } from './Landing'
export { Login, Register, ForgotPassword } from './Auth'
